language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -qU tox tox-travis flake8 coverage coveralls

script:
  - tox

before_script:
  - flake8 .

after_success:
  - coveralls
